AWSTemplateFormatVersion: '2010-09-09'
Description: book-word-template
Resources:
  # Email, Id, NickName, State, Role, ReadingIds, CreateTime, LastLoginTime
  userTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'Email'
          AttributeType: 'S'
        - AttributeName: 'Id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'Email'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: 'UserIdIndex'
          KeySchema:
            - AttributeName: 'Id'
              KeyType: 'HASH'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: 'bw-users'

  # Id, Name, Author, Url, CreateTime
  bookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'Id'
          AttributeType: 'S'
        - AttributeName: 'Name'
          AttributeType: 'S'
        - AttributeName: 'Author'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'Id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: 'BookNameIndex'
          KeySchema:
            - AttributeName: 'Name'
              KeyType: 'HASH'
            - AttributeName: 'Author'
              KeyType: 'RANGE'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: 'bw-books'

  # Id, Name, UserId, BookId, WordList, CreateTime
  wordBookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'Id'
          AttributeType: 'S'
        - AttributeName: 'UserId'
          AttributeType: 'S'
        - AttributeName: 'BookId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'Id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: 'WordBookUserIdIndex'
          KeySchema:
            - AttributeName: 'UserId'
              KeyType: 'HASH'
            - AttributeName: 'BookId'
              KeyType: 'RANGE'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: 'bw-word-books'

  # Id, Word, Translation, BookId, UserId, CreateTime
  wordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'Id'
          AttributeType: 'S'
        - AttributeName: 'BookId'
          AttributeType: 'S'
        - AttributeName: 'UserId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'Id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: 'WordUserIdIndex'
          KeySchema:
            - AttributeName: 'UserId'
              KeyType: 'HASH'
            - AttributeName: 'BookId'
              KeyType: 'RANGE'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: 'bw-words'

  bookBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: bw-book-bucket
